spring:
  # JDBC 설정
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  # H2 Database 설정
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true