DROP TABLE "store" IF EXISTS;
CREATE TABLE "store" (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(10) NOT NULL,
  HAS_DECAFFEINATED_MENU BOOLEAN NOT NULL,
  HAS_GRILLED_MENU BOOLEAN NOT NULL,
  IS_DELIVERY_AVAILABLE BOOLEAN NOT NULL,
  IS_DIRECT_MANAGED_STORE BOOLEAN NOT NULL,
  THUMBNAIL_URL VARCHAR(200) NOT NULL
);